language: python
python:
- '3.6'
install: pip install -e .
script:
- python -m pytest tests
deploy:
  provider: pypi
  user: charnley
  password:
    secure: XgE7X2sBiqyFDVoFTofTBd4T55E+bu9QbZi3FoJx2H4qfD+8kJZA+HStTUfRQmXEzuCPhO5ik9jn2enuebAVa7sCxKO1FLOXMhPlYZVFgMMQgekvZuQTE1f2sGSPo5DjxyqoDsxknXi1LUdm0v8m0pBVxNEL/FjSNEgBmby2+vGLoE1o/lKoIIyR7LWyJbzakLjeDDjd4H0jdq4ipYviCk5oznjk8ZpWRAaNrgX/jGp3vnNETD3/d3bKenm4foDlbL+t6BudHB26NIkrQV8O3McbA/3b6cBLsBRUEjR7+slQeWHaDlTegs/WKP/u00hsAbCKOZg69IVVudMIBFag397jZMYJ/aC8cYNcsoeSzYOfYkyAT3Cf0qDXrFR3MkC9oRpehmvZ+Sdl5EETflSCkahwvg3YTS+dmbFiV/oZxklvS8JFVa+nqFmJlTs8fjcg+XYWr1uP84n51XtUzSbaIobS0D0VTRBONfuwPxiL0GFeCZcpowxpOY/85m7s6Zz/EomVTMA30zHR9fpKQjXD2A91W3EcZEv0a2gn1TgaDxS4u22Q/4Ul+x2QszhK/KpyVGZrfh5832weSrlgWpXZdHFK1AiayW2h83qPdWsADtb6AanxwlNRq/4lNnI4ousNGm6y0XKelD6AnOkbHKsVq4LuOJqRjfaCEK2QgxAgMng=
  on:
    tags: true
    branch: master
    condition: ${TRAVIS_PYTHON_VERSION} = "3.6"
